remote_theme: pages-themes/slate@v0.2.0
plugins:
- jekyll-remote-theme # add this line to the plugins list if you already have one
title: Amanda's Portfolio
description: Here is a site for my portfolio work. Bookmark if you'd like to keep updated on my latest works
